runtime: plugin
action:
  title: Get Config
  description: "Get a configuration value"
  arguments:
    - name: key
      title: Key
      description: The configuration key to get (e.g., auth_kratos_db_host)
      required: true
  options:
    - name: vault
      title: Vault
      description: Get from encrypted vault (secrets)
      type: bool
      default: false
    - name: chassis
      shorthand: c
      title: Chassis
      description: Chassis name (e.g., platform.foundation.cluster)
      type: string
      required: true
